**Objective:**
To develop a Retrieval-Augmented Generation (RAG) application using the LlamaIndex framework. This application will also be evaluated using the RAGAS framework for enhanced performance metrics.

**Key Details:**
- **Input:** A PDF file located in the car_brochure directory, containing a car brochure.
- **Goal:** Enable the application to accurately answer user queries based on the contents of the PDF.
-**LLM:** Leveraging Cohere for the language model.
- **Embeddings:** Generated using the Hugging Face model "BAAI/bge-small-en-v1" for semantic understanding.

**Installing the dependencies**

In [ ]:
pip install -r requirements.txt

Requirement already satisfied: langchain in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 1)) (0.3.14)
Collecting langchain-community (from -r requirements.txt (line 2))
  Downloading langchain_community-0.3.14-py3-none-any.whl.metadata (2.9 kB)
Collecting pypdf (from -r requirements.txt (line 3))
  Downloading pypdf-5.1.0-py3-none-any.whl.metadata (7.2 kB)
Collecting chromadb (from -r requirements.txt (line 4))
  Downloading chromadb-0.6.2-py3-none-any.whl.metadata (6.8 kB)
Collecting langchain-cohere (from -r requirements.txt (line 5))
  Downloading langchain_cohere-0.3.4-py3-none-any.whl.metadata (6.7 kB)
Collecting python-dotenv (from -r requirements.txt (line 6))
  Downloading python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Collecting llama-index-embeddings-huggingface (from -r requirements.txt (line 7))
  Downloading llama_index_embeddings_huggingface-0.5.0-py3-none-any.whl.metadata (767 bytes)
Collecting llama-index-llms-huggingface (from -r requirements.txt (line 8))
  Downloading llama_index_llms_huggingface-0.4.2-py3-none-any.whl.metadata (2.9 kB)
Collecting llama-index-llms-cohere (from -r requirements.txt (line 9))
  Downloading llama_index_llms_cohere-0.4.0-py3-none-any.whl.metadata (5.2 kB)
Collecting llama-index (from -r requirements.txt (line 10))
  Downloading llama_index-0.12.10-py3-none-any.whl.metadata (11 kB)
Collecting llama-index-vector-stores-chroma (from -r requirements.txt (line 11))
  Downloading llama_index_vector_stores_chroma-0.4.1-py3-none-any.whl.metadata (696 bytes)
Collecting ragas (from -r requirements.txt (line 12))
  Downloading ragas-0.2.10-py3-none-any.whl.metadata (8.2 kB)
Collecting rapidfuzz (from -r requirements.txt (line 13))
  Downloading rapidfuzz-3.11.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Requirement already satisfied: PyYAML>=5.3 in /usr/local/lib/python3.10/dist-packages (from langchain->-r requirements.txt (line 1)) (6.0.2)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.10/dist-packages (from langchain->-r requirements.txt (line 1)) (2.0.36)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.10/dist-packages (from langchain->-r requirements.txt (line 1)) (3.11.11)
Requirement already satisfied: async-timeout<5.0.0,>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from langchain->-r requirements.txt (line 1)) (4.0.3)
Requirement already satisfied: langchain-core<0.4.0,>=0.3.29 in /usr/local/lib/python3.10/dist-packages (from langchain->-r requirements.txt (line 1)) (0.3.29)
Requirement already satisfied: langchain-text-splitters<0.4.0,>=0.3.3 in /usr/local/lib/python3.10/dist-packages (from langchain->-r requirements.txt (line 1)) (0.3.5)
Requirement already satisfied: langsmith<0.3,>=0.1.17 in /usr/local/lib/python3.10/dist-packages (from langchain->-r requirements.txt (line 1)) (0.2.10)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from langchain->-r requirements.txt (line 1)) (1.26.4)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.10/dist-packages (from langchain->-r requirements.txt (line 1)) (2.10.4)
Requirement already satisfied: requests<3,>=2 in /usr/local/lib/python3.10/dist-packages (from langchain->-r requirements.txt (line 1)) (2.32.3)
Requirement already satisfied: tenacity!=8.4.0,<10,>=8.1.0 in /usr/local/lib/python3.10/dist-packages (from langchain->-r requirements.txt (line 1)) (9.0.0)
Collecting dataclasses-json<0.7,>=0.5.7 (from langchain-community->-r requirements.txt (line 2))
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting httpx-sse<0.5.0,>=0.4.0 (from langchain-community->-r requirements.txt (line 2))
  Downloading httpx_sse-0.4.0-py3-none-any.whl.metadata (9.0 kB)
Collecting pydantic-settings<3.0.0,>=2.4.0 (from langchain-community->-r requirements.txt (line 2))
  Downloading pydantic_settings-2.7.1-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: typing_extensions>=4.0 in /usr/local/lib/python3.10/dist-packages (from pypdf->-r requirements.txt (line 3)) (4.12.2)
Collecting build>=1.0.3 (from chromadb->-r requirements.txt (line 4))
  Downloading build-1.2.2.post1-py3-none-any.whl.metadata (6.5 kB)
Collecting chroma-hnswlib==0.7.6 (from chromadb->-r requirements.txt (line 4))
  Downloading chroma_hnswlib-0.7.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (252 bytes)
Collecting fastapi>=0.95.2 (from chromadb->-r requirements.txt (line 4))
  Downloading fastapi-0.115.6-py3-none-any.whl.metadata (27 kB)
Collecting uvicorn>=0.18.3 (from uvicorn[standard]>=0.18.3->chromadb->-r requirements.txt (line 4))
  Downloading uvicorn-0.34.0-py3-none-any.whl.metadata (6.5 kB)
Collecting posthog>=2.4.0 (from chromadb->-r requirements.txt (line 4))
  Downloading posthog-3.7.5-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting onnxruntime>=1.14.1 (from chromadb->-r requirements.txt (line 4))
  Downloading onnxruntime-1.20.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (4.5 kB)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from chromadb->-r requirements.txt (line 4)) (1.29.0)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb->-r requirements.txt (line 4))
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.29.0-py3-none-any.whl.metadata (2.2 kB)
Collecting opentelemetry-instrumentation-fastapi>=0.41b0 (from chromadb->-r requirements.txt (line 4))
  Downloading opentelemetry_instrumentation_fastapi-0.50b0-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from chromadb->-r requirements.txt (line 4)) (1.29.0)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.10/dist-packages (from chromadb->-r requirements.txt (line 4)) (0.21.0)
Collecting pypika>=0.48.9 (from chromadb->-r requirements.txt (line 4))
  Downloading PyPika-0.48.9.tar.gz (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.3/67.3 kB 4.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.10/dist-packages (from chromadb->-r requirements.txt (line 4)) (4.67.1)
Collecting overrides>=7.3.1 (from chromadb->-r requirements.txt (line 4))
  Downloading overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.10/dist-packages (from chromadb->-r requirements.txt (line 4)) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.10/dist-packages (from chromadb->-r requirements.txt (line 4)) (1.69.0)
Collecting bcrypt>=4.0.1 (from chromadb->-r requirements.txt (line 4))
  Downloading bcrypt-4.2.1-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (9.8 kB)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from chromadb->-r requirements.txt (line 4)) (0.15.1)
Collecting kubernetes>=28.1.0 (from chromadb->-r requirements.txt (line 4))
  Downloading kubernetes-31.0.0-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting mmh3>=4.0.1 (from chromadb->-r requirements.txt (line 4))
  Downloading mmh3-5.0.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (14 kB)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.10/dist-packages (from chromadb->-r requirements.txt (line 4)) (3.10.13)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.10/dist-packages (from chromadb->-r requirements.txt (line 4)) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from chromadb->-r requirements.txt (line 4)) (13.9.4)
Collecting cohere<6.0,>=5.5.6 (from langchain-cohere->-r requirements.txt (line 5))
  Downloading cohere-5.13.6-py3-none-any.whl.metadata (3.5 kB)
Collecting langchain-experimental<0.4.0,>=0.3.0 (from langchain-cohere->-r requirements.txt (line 5))
  Downloading langchain_experimental-0.3.4-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: pandas>=1.4.3 in /usr/local/lib/python3.10/dist-packages (from langchain-cohere->-r requirements.txt (line 5)) (2.2.2)
Requirement already satisfied: tabulate<0.10.0,>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from langchain-cohere->-r requirements.txt (line 5)) (0.9.0)
Requirement already satisfied: huggingface-hub>=0.19.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface->-r requirements.txt (line 7)) (0.27.1)
Collecting llama-index-core<0.13.0,>=0.12.0 (from llama-index-embeddings-huggingface->-r requirements.txt (line 7))
  Downloading llama_index_core-0.12.10.post1-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: sentence-transformers>=2.6.1 in /usr/local/lib/python3.10/dist-packages (from llama-index-embeddings-huggingface->-r requirements.txt (line 7)) (3.3.1)
Collecting text-generation<0.8.0,>=0.7.0 (from llama-index-llms-huggingface->-r requirements.txt (line 8))
  Downloading text_generation-0.7.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: torch<3.0.0,>=2.1.2 in /usr/local/lib/python3.10/dist-packages (from llama-index-llms-huggingface->-r requirements.txt (line 8)) (2.5.1+cu121)
Requirement already satisfied: transformers<5.0.0,>=4.37.0 in /usr/local/lib/python3.10/dist-packages (from transformers[torch]<5.0.0,>=4.37.0->llama-index-llms-huggingface->-r requirements.txt (line 8)) (4.47.1)
Collecting llama-index-agent-openai<0.5.0,>=0.4.0 (from llama-index->-r requirements.txt (line 10))
  Downloading llama_index_agent_openai-0.4.1-py3-none-any.whl.metadata (726 bytes)
Collecting llama-index-cli<0.5.0,>=0.4.0 (from llama-index->-r requirements.txt (line 10))
  Downloading llama_index_cli-0.4.0-py3-none-any.whl.metadata (1.5 kB)
Collecting llama-index-embeddings-openai<0.4.0,>=0.3.0 (from llama-index->-r requirements.txt (line 10))
  Downloading llama_index_embeddings_openai-0.3.1-py3-none-any.whl.metadata (684 bytes)
Collecting llama-index-indices-managed-llama-cloud>=0.4.0 (from llama-index->-r requirements.txt (line 10))
  Downloading llama_index_indices_managed_llama_cloud-0.6.3-py3-none-any.whl.metadata (3.8 kB)
Collecting llama-index-llms-openai<0.4.0,>=0.3.0 (from llama-index->-r requirements.txt (line 10))
  Downloading llama_index_llms_openai-0.3.13-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-index-multi-modal-llms-openai<0.5.0,>=0.4.0 (from llama-index->-r requirements.txt (line 10))
  Downloading llama_index_multi_modal_llms_openai-0.4.2-py3-none-any.whl.metadata (726 bytes)
Collecting llama-index-program-openai<0.4.0,>=0.3.0 (from llama-index->-r requirements.txt (line 10))
  Downloading llama_index_program_openai-0.3.1-py3-none-any.whl.metadata (764 bytes)
Collecting llama-index-question-gen-openai<0.4.0,>=0.3.0 (from llama-index->-r requirements.txt (line 10))
  Downloading llama_index_question_gen_openai-0.3.0-py3-none-any.whl.metadata (783 bytes)
Collecting llama-index-readers-file<0.5.0,>=0.4.0 (from llama-index->-r requirements.txt (line 10))
  Downloading llama_index_readers_file-0.4.3-py3-none-any.whl.metadata (5.4 kB)
Collecting llama-index-readers-llama-parse>=0.4.0 (from llama-index->-r requirements.txt (line 10))
  Downloading llama_index_readers_llama_parse-0.4.0-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: nltk>3.8.1 in /usr/local/lib/python3.10/dist-packages (from llama-index->-r requirements.txt (line 10)) (3.9.1)
Collecting datasets (from ragas->-r requirements.txt (line 12))
  Downloading datasets-3.2.0-py3-none-any.whl.metadata (20 kB)
Collecting tiktoken (from ragas->-r requirements.txt (line 12))
  Downloading tiktoken-0.8.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting langchain_openai (from ragas->-r requirements.txt (line 12))
  Downloading langchain_openai-0.3.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.10/dist-packages (from ragas->-r requirements.txt (line 12)) (1.6.0)
Collecting appdirs (from ragas->-r requirements.txt (line 12))
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: openai>1 in /usr/local/lib/python3.10/dist-packages (from ragas->-r requirements.txt (line 12)) (1.59.4)
Collecting pysbd>=0.3.4 (from ragas->-r requirements.txt (line 12))
  Downloading pysbd-0.3.4-py3-none-any.whl.metadata (6.1 kB)
Collecting diskcache>=5.6.3 (from ragas->-r requirements.txt (line 12))
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r requirements.txt (line 1)) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r requirements.txt (line 1)) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r requirements.txt (line 1)) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r requirements.txt (line 1)) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r requirements.txt (line 1)) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r requirements.txt (line 1)) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r requirements.txt (line 1)) (1.18.3)
Requirement already satisfied: packaging>=19.1 in /usr/local/lib/python3.10/dist-packages (from build>=1.0.3->chromadb->-r requirements.txt (line 4)) (24.2)
Collecting pyproject_hooks (from build>=1.0.3->chromadb->-r requirements.txt (line 4))
  Downloading pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: tomli>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from build>=1.0.3->chromadb->-r requirements.txt (line 4)) (2.2.1)
Collecting fastavro<2.0.0,>=1.9.4 (from cohere<6.0,>=5.5.6->langchain-cohere->-r requirements.txt (line 5))
  Downloading fastavro-1.10.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.5 kB)
Collecting parameterized<0.10.0,>=0.9.0 (from cohere<6.0,>=5.5.6->langchain-cohere->-r requirements.txt (line 5))
  Downloading parameterized-0.9.0-py2.py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: pydantic-core<3.0.0,>=2.18.2 in /usr/local/lib/python3.10/dist-packages (from cohere<6.0,>=5.5.6->langchain-cohere->-r requirements.txt (line 5)) (2.27.2)
Collecting types-requests<3.0.0,>=2.0.0 (from cohere<6.0,>=5.5.6->langchain-cohere->-r requirements.txt (line 5))
  Downloading types_requests-2.32.0.20241016-py3-none-any.whl.metadata (1.9 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7,>=0.5.7->langchain-community->-r requirements.txt (line 2))
  Downloading marshmallow-3.25.1-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7,>=0.5.7->langchain-community->-r requirements.txt (line 2))
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Collecting starlette<0.42.0,>=0.40.0 (from fastapi>=0.95.2->chromadb->-r requirements.txt (line 4))
  Downloading starlette-0.41.3-py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.10/dist-packages (from httpx>=0.27.0->chromadb->-r requirements.txt (line 4)) (3.7.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx>=0.27.0->chromadb->-r requirements.txt (line 4)) (2024.12.14)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx>=0.27.0->chromadb->-r requirements.txt (line 4)) (1.0.7)
Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from httpx>=0.27.0->chromadb->-r requirements.txt (line 4)) (3.10)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb->-r requirements.txt (line 4)) (0.14.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface->-r requirements.txt (line 7)) (3.16.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface->-r requirements.txt (line 7)) (2024.10.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb->-r requirements.txt (line 4)) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb->-r requirements.txt (line 4)) (2.8.2)
Requirement already satisfied: google-auth>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb->-r requirements.txt (line 4)) (2.27.0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb->-r requirements.txt (line 4)) (1.8.0)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb->-r requirements.txt (line 4)) (1.3.1)
Requirement already satisfied: oauthlib>=3.2.2 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb->-r requirements.txt (line 4)) (3.2.2)
Requirement already satisfied: urllib3>=1.24.2 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb->-r requirements.txt (line 4)) (2.3.0)
Collecting durationpy>=0.7 (from kubernetes>=28.1.0->chromadb->-r requirements.txt (line 4))
  Downloading durationpy-0.9-py3-none-any.whl.metadata (338 bytes)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.10/dist-packages (from langchain-core<0.4.0,>=0.3.29->langchain->-r requirements.txt (line 1)) (1.33)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from langsmith<0.3,>=0.1.17->langchain->-r requirements.txt (line 1)) (1.0.0)
Requirement already satisfied: deprecated>=1.2.9.3 in /usr/local/lib/python3.10/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface->-r requirements.txt (line 7)) (1.2.15)
Collecting dirtyjson<2.0.0,>=1.0.8 (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface->-r requirements.txt (line 7))
  Downloading dirtyjson-1.0.8-py3-none-any.whl.metadata (11 kB)
Collecting filetype<2.0.0,>=1.2.0 (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface->-r requirements.txt (line 7))
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.10/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface->-r requirements.txt (line 7)) (3.4.2)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.10/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-embeddings-huggingface->-r requirements.txt (line 7)) (11.1.0)

- If you are having config issues uninstall transformer huggingface-hub and reinstall them as mentioned in the cell below.

In [ ]:
#!pip uninstall transformers huggingface-hub -y
#!pip install transformers huggingface-hub

Found existing installation: transformers 4.47.1
Uninstalling transformers-4.47.1:
  Successfully uninstalled transformers-4.47.1
Found existing installation: huggingface-hub 0.27.0
Uninstalling huggingface-hub-0.27.0:
  Successfully uninstalled huggingface-hub-0.27.0

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
import os
from dotenv import load_dotenv

load_dotenv()
openai_api_key=os.getenv('openai_api')
os.environ["OPENAI_API_KEY"] = openai_api_key

In [ ]:
#Loading the libraries

from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.core import Settings
from llama_index.embeddings.openai import OpenAIEmbedding

#We are setting the Settings object
Settings.embed_model = OpenAIEmbedding(model="text-embedding-3-large")
#Settings.embed_model=HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")

In [ ]:
import os

# Create a new directory to store the pdf file for input
directory_name = "car_brochure"
os.makedirs(directory_name, exist_ok=True)

print(f"Directory '{directory_name}' created successfully!")

Directory 'car_brochure' created successfully!

In [ ]:
from dotenv import load_dotenv

load_dotenv()
hf_token=os.getenv('hugging_face_api')

In [ ]:
#Loading the libraries

import chromadb
from llama_index.vector_stores.chroma import ChromaVectorStore
from llama_index.core import VectorStoreIndex,SimpleDirectoryReader,get_response_synthesizer
from llama_index.core.retrievers import VectorIndexRetriever
from llama_index.core.query_engine import RetrieverQueryEngine
from llama_index.llms.cohere import Cohere
from llama_index.core import StorageContext
from llama_index.core.postprocessor import SimilarityPostprocessor
from llama_index.llms.openai import OpenAI
from dotenv import load_dotenv
import os

#Load the env file
load_dotenv()
cohere_token=os.getenv('cohere_api')

#llm=Cohere(api_key=cohere_token)
#Settings.llm=llm

Settings.llm=OpenAI(model="gpt-4o")

documents=SimpleDirectoryReader('/content/car_brochure').load_data()

# initialize chroma client, setting path to save data
db = chromadb.PersistentClient(path="./chroma_db")


# create collection
chroma_collection = db.get_or_create_collection("quickstart")


# assign chroma as the vector_store to the context
vector_store = ChromaVectorStore(chroma_collection=chroma_collection)

storage_context = StorageContext.from_defaults(vector_store=vector_store)

# create/build your index
index = VectorStoreIndex.from_documents(
    documents
)

#Configure your retriever
retriever=VectorIndexRetriever(
    index=index,
    similarity_top_k=10

)
#Configure response synthesizer
response_synthesizer=get_response_synthesizer()

#assemble query engine
query_engine=RetrieverQueryEngine(
    retriever=retriever,
    response_synthesizer=response_synthesizer,
    node_postprocessors=[SimilarityPostprocessor(similarity_cutoff=0.3)]
)

**Stages of querying**

However, there is more to querying than initially meets the eye. Querying consists of three distinct stages:

**Retrieval** is when you find and return the most relevant documents for your query from your Index. As previously discussed in indexing, the most common type of retrieval is "top-k" semantic retrieval, but there are many other retrieval strategies.

**Postprocessing** is when the Nodes retrieved are optionally reranked, transformed, or filtered, for instance by requiring that they have specific metadata such as keywords attached.

**Response synthesis** is when your query, your most-relevant data and your prompt are combined and sent to your LLM to return a response.

In [ ]:
# Create a Query Engine
response = query_engine.query("What are the interior highlights of the Hyundai Creta?")
print(response)

The interior highlights of the Hyundai Creta include a refined cockpit, comfortable second row, seamlessly integrated infotainment and cluster screen, power driver seat with 8-way adjustment, rear window sunshade, and all-black interiors with brass-colored inserts. Additionally, it features exclusive black upholstery with brass stitching and piping, sporty metal pedals, and a digital cluster with a color TFT MID.

In [ ]:
# Create a Query Engine
response = query_engine.query("What were the primary tasks used to evaluate the Transformer model?")
print(response)

The primary tasks used to evaluate the Transformer model were the WMT 2014 English-to-German and English-to-French translation tasks.

In [ ]:
# Create a Query Engine
response = query_engine.query("What are the engine configurations and their associated maximum power outputs for the Hyundai CRETA?")
print(response)

The Hyundai CRETA offers three engine configurations: a 1.5-liter petrol engine, a 1.5-liter petrol turbo engine, and a 1.5-liter diesel engine. The 1.5-liter petrol engine is available with both manual and intelligent variable transmissions. The 1.5-liter petrol turbo engine comes with a 7-speed dual-clutch transmission. The 1.5-liter diesel engine is available with both 6-speed manual and automatic transmissions. The maximum power outputs for these engines are not specified in the provided information.

In [ ]:
# create a query engine using index.
query_engine = index.as_query_engine()
response = query_engine.query("How does the SX(O) variant differ from the S variant of the Creta?")
print(response)

The SX(O) variant of the Hyundai Creta has several features that make it a more attractive and powerful option than the S variant.

In terms of design and aesthetics, the SX(O) has a bold and charismatic appearance thanks to its black chrome parametric radiator grille, horizon LED positioning lamps & DRLs, and quad beam LED headlamps. The rear of the vehicle is equally impressive with connecting LED tail lamps and an integrated rear spoiler with an LED HMSL. The side view is enhanced by the diamond-cut R17 alloys.

Additionally, the SX(O) variant offers a more powerful and diverse driving experience. The 1.5l petrol turbo engine provides ample power, and the paddle shifters and different traction control modes (snow, mud, sand) allow for a dynamic driving performance.

In [ ]:
# Create a Query Engine
response = query_engine.query("What are the available color options for the Hyundai Creta?")
print(response)

The Hyundai Creta seems to be available in at least two colour options: black and brass inserts, or black chrome.

**EVALUATING THE QUERY ENGINE USING RAGES**

In [ ]:
from dotenv import load_dotenv
import os

load_dotenv()

True

In [ ]:
openai_api_key=os.getenv('openai_api')

In [ ]:
#Step1 : To generate the test data lets initalize the TestsetGenerator object with the corresponding generator llm

from ragas.testset import TestsetGenerator
from llama_index.embeddings.openai import   OpenAIEmbedding
from llama_index.llms.openai import OpenAI



# generator with openai models
#openai_api_key="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"
generator_llm = OpenAI(model="gpt-4o",api_key=openai_api_key)
embeddings = OpenAIEmbedding(model="text-embedding-3-small",api_key=openai_api_key)

generator = TestsetGenerator.from_llama_index(
    llm=generator_llm,
    embedding_model=embeddings,
)

In [ ]:
#Step2 :To generate the questions from the document using the generator above

# generate testset
testset = generator.generate_with_llamaindex_docs(
    documents,
    testset_size=5,
)

Applying HeadlinesExtractor:   0%|          | 0/10 [00:00<?, ?it/s]

Applying HeadlineSplitter:   0%|          | 0/11 [00:00<?, ?it/s]

ERROR:ragas.testset.transforms.engine:unable to apply transformation: 'headlines' property not found in this node

Applying SummaryExtractor:   0%|          | 0/19 [00:00<?, ?it/s]

WARNING:ragas.testset.transforms.base:Property 'summary' already exists in node '96fbbf'. Skipping!
WARNING:ragas.testset.transforms.base:Property 'summary' already exists in node 'e6d98c'. Skipping!
WARNING:ragas.testset.transforms.base:Property 'summary' already exists in node 'a29ee8'. Skipping!
WARNING:ragas.testset.transforms.base:Property 'summary' already exists in node '223d65'. Skipping!
WARNING:ragas.testset.transforms.base:Property 'summary' already exists in node 'c33e06'. Skipping!
WARNING:ragas.testset.transforms.base:Property 'summary' already exists in node '69ba2a'. Skipping!
WARNING:ragas.testset.transforms.base:Property 'summary' already exists in node '47755f'. Skipping!
WARNING:ragas.testset.transforms.base:Property 'summary' already exists in node 'a9609f'. Skipping!
WARNING:ragas.testset.transforms.base:Property 'summary' already exists in node 'df7e29'. Skipping!

Applying CustomNodeFilter:   0%|          | 0/2 [00:00<?, ?it/s]

Applying [EmbeddingExtractor, ThemesExtractor, NERExtractor]:   0%|          | 0/23 [00:00<?, ?it/s]

WARNING:ragas.testset.transforms.base:Property 'summary_embedding' already exists in node '69ba2a'. Skipping!
WARNING:ragas.testset.transforms.base:Property 'summary_embedding' already exists in node '96fbbf'. Skipping!
WARNING:ragas.testset.transforms.base:Property 'summary_embedding' already exists in node 'e6d98c'. Skipping!
WARNING:ragas.testset.transforms.base:Property 'summary_embedding' already exists in node '47755f'. Skipping!
WARNING:ragas.testset.transforms.base:Property 'summary_embedding' already exists in node '223d65'. Skipping!
WARNING:ragas.testset.transforms.base:Property 'summary_embedding' already exists in node 'a29ee8'. Skipping!
WARNING:ragas.testset.transforms.base:Property 'summary_embedding' already exists in node 'df7e29'. Skipping!
WARNING:ragas.testset.transforms.base:Property 'summary_embedding' already exists in node 'a9609f'. Skipping!
WARNING:ragas.testset.transforms.base:Property 'summary_embedding' already exists in node 'c33e06'. Skipping!

Applying [CosineSimilarityBuilder, OverlapScoreBuilder]:   0%|          | 0/2 [00:00<?, ?it/s]

Generating personas:   0%|          | 0/3 [00:00<?, ?it/s]

Generating Scenarios:   0%|          | 0/2 [00:00<?, ?it/s]

Generating Samples:   0%|          | 0/5 [00:00<?, ?it/s]

WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29725, Requested 1812. Please try again in 3.074s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29715, Requested 1812. Please try again in 3.054s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.

In [ ]:
df= testset.to_pandas()
df.head()

,user_input,reference_contexts,reference,synthesizer_name
0,What role does Multi-Head Attention play in th...,[Recurrent models typically factor computation...,Multi-Head Attention in the Transformer model ...,single_hop_specifc_query_synthesizer
1,How does Multi-Head Attention enhance the perf...,[Recurrent models typically factor computation...,Multi-Head Attention in the Transformer model ...,single_hop_specifc_query_synthesizer
2,How does the Transformer model use attention m...,[<1-hop>\n\nRecurrent models typically factor ...,The Transformer model uses attention mechanism...,multi_hop_abstract_query_synthesizer
3,How does the Transformer model's encoder utili...,[<1-hop>\n\nRecurrent models typically factor ...,The Transformer model's encoder utilizes a sta...,multi_hop_abstract_query_synthesizer
4,How does the Transformer model utilize the enc...,[<1-hop>\n\nRecurrent models typically factor ...,The Transformer model utilizes the encoder to ...,multi_hop_abstract_query_synthesizer

In [ ]:
print(df['user_input'][0]) #Query
print(df['reference_contexts'][0]) #Retrieved docs
print(df['reference'][0]) #Response from llm

What role does Multi-Head Attention play in the Transformer model?
['Recurrent models typically factor computation along the symbol positions of the input and output sequences. Aligning the positions to steps in computation time, they generate a sequence of hidden states ht, as a function of the previous hidden state ht−1 and the input for position t. This inherently sequential nature precludes parallelization within training examples, which becomes critical at longer sequence lengths, as memory constraints limit batching across examples. Recent work has achieved signiﬁcant improvements in computational efﬁciency through factorization tricks [18] and conditional computation [26], while also improving model performance in case of the latter. The fundamental constraint of sequential computation, however, remains. Attention mechanisms have become an integral part of compelling sequence modeling and transduc- tion models in various tasks, allowing modeling of dependencies without regard to their distance in the input or output sequences [2, 16]. In all but a few cases [22], however, such attention mechanisms are used in conjunction with a recurrent network. In this work we propose the Transformer, a model architecture eschewing recurrence and instead relying entirely on an attention mechanism to draw global dependencies between input and output. The Transformer allows for signiﬁcantly more parallelization and can reach a new state of the art in translation quality after being trained for as little as twelve hours on eight P100 GPUs. 2 Background The goal of reducing sequential computation also forms the foundation of the Extended Neural GPU [20], ByteNet [15] and ConvS2S [8], all of which use convolutional neural networks as basic building block, computing hidden representations in parallel for all input and output positions. In these models, the number of operations required to relate signals from two arbitrary input or output positions grows in the distance between positions, linearly for ConvS2S and logarithmically for ByteNet. This makes it more difﬁcult to learn dependencies between distant positions [ 11]. In the Transformer this is reduced to a constant number of operations, albeit at the cost of reduced effective resolution due to averaging attention-weighted positions, an effect we counteract with Multi-Head Attention as described in section 3.2. Self-attention, sometimes called intra-attention is an attention mechanism relating different positions of a single sequence in order to compute a representation of the sequence. Self-attention has been used successfully in a variety of tasks including reading comprehension, abstractive summarization, textual entailment and learning task-independent sentence representations [4, 22, 23, 19]. End-to-end memory networks are based on a recurrent attention mechanism instead of sequence- aligned recurrence and have been shown to perform well on simple-language question answering and language modeling tasks [28]. To the best of our knowledge, however, the Transformer is the ﬁrst transduction model relying entirely on self-attention to compute representations of its input and output without using sequence- aligned RNNs or convolution. In the following sections, we will describe the Transformer, motivate self-attention and discuss its advantages over models such as [14, 15] and [8]. 3 Model Architecture Most competitive neural sequence transduction models have an encoder-decoder structure [5, 2, 29]. Here, the encoder maps an input sequence of symbol representations (x1,...,x n) to a sequence of continuous representations z = (z1,...,z n). Given z, the decoder then generates an output sequence (y1,...,y m) of symbols one element at a time. At each step the model is auto-regressive [9], consuming the previously generated symbols as additional input when generating the next. The Transformer follows this overall architecture using stacked self-attention and point-wise, fully connected layers for both the encoder and decoder, shown in the left and right halves of Figure 1, respectively. 3.1']
Multi-Head Attention in the Transformer model helps counteract the reduced effective resolution due to averaging attention-weighted positions, allowing the model to draw global dependencies between input and output more effectively.

- Now that we have our test data lets now use the test  data to test our query engine and evaluate it

**Evaluating the Query Engine**

Now that we have a QueryEngine for the VectorStoreIndex we can use the llama_index integration Ragas has to evaluate it.

In order to run an evaluation with Ragas and LlamaIndex you need 3 things

- **LlamaIndex QueryEngine:** what we will be evaluating
- **Metrics:** Ragas defines a set of metrics that can measure different aspects of the QueryEngine.
- **Questions:** A list of questions that ragas will test the QueryEngine against.
 Ideally you should use that you see in production so that the distribution of question with which we evaluate matches the distribution of questions seen in production. This ensures that the scores reflect the performance seen in production but to start off we'll be using a few example question.

Now lets import the metrics we will be using to evaluate

In [ ]:

from ragas.metrics import(
    ContextPrecision,
    ContextRecall,
    Faithfulness,
    AnswerRelevancy
)

#Initiatte the metrics with evaluator llm

from ragas.llms import LlamaIndexLLMWrapper
print(openai_api_key)
evaluator_llm=LlamaIndexLLMWrapper(OpenAI(model="gpt-4o",api_key=openai_api_key))

metrics=[
    Faithfulness(llm=evaluator_llm),
    AnswerRelevancy(llm=evaluator_llm),
    ContextPrecision(llm=evaluator_llm),
    ContextRecall(llm=evaluator_llm)
]

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

In [ ]:
# convert to Ragas Evaluation Dataset
ragas_dataset = testset.to_evaluation_dataset()
ragas_dataset

EvaluationDataset(features=['user_input', 'reference_contexts', 'reference'], len=5)

In [ ]:
#Step3 :  Last step , Run the evaluate method and the result
from ragas.integrations.llama_index import evaluate
import os
os.environ["OPENAI_API_KEY"] = openai_api_key

result = evaluate(
    query_engine=query_engine,
    metrics=metrics,
    dataset=ragas_dataset,
)
print(result)
result.to_pandas()

Running Query Engine:   0%|          | 0/5 [00:00<?, ?it/s]

Evaluating:   0%|          | 0/20 [00:00<?, ?it/s]

WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29970, Requested 477. Please try again in 894ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29965, Requested 477. Please try again in 884ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29940, Requested 495. Please try again in 870ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29940, Requested 495. Please try again in 870ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29932, Requested 495. Please try again in 854ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29891, Requested 551. Please try again in 884ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29890, Requested 551. Please try again in 882ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29878, Requested 551. Please try again in 858ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29864, Requested 1029. Please try again in 1.786s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29816, Requested 1075. Please try again in 1.782s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29716, Requested 1195. Please try again in 1.822s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29657, Requested 1681. Please try again in 2.676s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29651, Requested 1690. Please try again in 2.682s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.4427761094711031 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29944, Requested 495. Please try again in 878ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.5306137132831927 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29944, Requested 495. Please try again in 878ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.5516172436730615 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29887, Requested 551. Please try again in 876ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0033182475351743 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29882, Requested 551. Please try again in 866ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.5817253972804841 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29882, Requested 551. Please try again in 866ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29844, Requested 1063. Please try again in 1.814s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29532, Requested 487. Please try again in 38ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29729, Requested 2254. Please try again in 3.966s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29643, Requested 2315. Please try again in 3.916s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.97486891504587 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29922, Requested 1029. Please try again in 1.902s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.444243647062281 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29886, Requested 1075. Please try again in 1.921s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.759483692772988 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29799, Requested 1195. Please try again in 1.988s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.9225947529650393 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29344, Requested 1063. Please try again in 814ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.931650587079782 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29751, Requested 1681. Please try again in 2.864s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.1620157513387226 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29745, Requested 1690. Please try again in 2.87s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 28882, Requested 2273. Please try again in 2.31s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.2021686536813552 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 28829, Requested 2254. Please try again in 2.166s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.5286624644492683 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29970, Requested 2315. Please try again in 4.57s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.9121693258099635 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29298, Requested 2273. Please try again in 3.142s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29975, Requested 2145. Please try again in 4.24s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29862, Requested 2254. Please try again in 4.232s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29795, Requested 2315. Please try again in 4.22s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29900, Requested 8533. Please try again in 16.866s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29881, Requested 8542. Please try again in 16.846s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29776, Requested 8651. Please try again in 16.854s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29721, Requested 8712. Please try again in 16.866s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.7860738463233654 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29426, Requested 2145. Please try again in 3.142s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._achat in 1.0 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-9yL9cBriixM9iQfidMemqmAk on tokens per min (TPM): Limit 30000, Used 29298, Requested 2273. Please try again in 3.142s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}.

{'faithfulness': nan, 'answer_relevancy': 0.9690, 'context_precision': 0.8368, 'context_recall': nan}

,user_input,retrieved_contexts,reference_contexts,response,reference,faithfulness,answer_relevancy,context_precision,context_recall
0,What role does Multi-Head Attention play in th...,[Scaled Dot-Product Attention\n Multi-Head Att...,[Recurrent models typically factor computation...,Multi-Head Attention in the Transformer model ...,Multi-Head Attention in the Transformer model ...,NaN,0.989733,0.916667,NaN
1,How does Multi-Head Attention enhance the perf...,[Scaled Dot-Product Attention\n Multi-Head Att...,[Recurrent models typically factor computation...,Multi-Head Attention enhances the performance ...,Multi-Head Attention in the Transformer model ...,NaN,1.000000,1.000000,NaN
2,How does the Transformer model use attention m...,[Recurrent models typically factor computation...,[<1-hop>\n\nRecurrent models typically factor ...,The Transformer model uses self-attention mech...,The Transformer model uses attention mechanism...,NaN,0.935615,NaN,NaN
3,How does the Transformer model's encoder utili...,[Recurrent models typically factor computation...,[<1-hop>\n\nRecurrent models typically factor ...,The Transformer model's encoder utilizes multi...,The Transformer model's encoder utilizes a sta...,NaN,0.985772,0.750000,NaN
4,How does the Transformer model utilize the enc...,[Recurrent models typically factor computation...,[<1-hop>\n\nRecurrent models typically factor ...,The Transformer model utilizes the encoder to ...,The Transformer model utilizes the encoder to ...,NaN,0.934096,0.680556,NaN

In [ ]:
#Final result for attention .pdf

print(result)

{'faithfulness': nan, 'answer_relevancy': 0.9690, 'context_precision': 0.8368, 'context_recall': nan}

In [ ]:
#Final scores for car brochure pdf
print(result)

{'faithfulness': 0.1667, 'answer_relevancy': 0.9638, 'context_precision': 0.5626, 'context_recall': 0.0000}

In [ ]:
result.to_pandas()

,user_input,retrieved_contexts,reference_contexts,response,reference,faithfulness,answer_relevancy,context_precision,context_recall
0,Wht featuers does the SX(O)Knight model of Hyu...,"[If dark is your style, CRETA Knight will make...",[Transmission Type 6-speed manual & 6-speed ma...,The SX(O)Knight model of Hyundai offers a rang...,The SX(O)Knight model of Hyundai offers featur...,NaN,0.989016,0.654444,NaN
1,What is the role of ISOFIX in vehicle safety f...,[6 Airbags standard\nOther features: ECM mirro...,[Safety Airbag Driver & passenger S S S S S S ...,ISOFIX is a safety feature in vehicles that pr...,ISOFIX is a safety feature included in vehicle...,0.166667,0.940179,0.000000,0.0
2,Considering the various transmission types and...,[Forward Collision - Avoidance Assist - \nJunc...,[<1-hop>\n\nTransmission Type 6-speed manual &...,The Hyundai model offers a personalized and sa...,The Hyundai model offers a range of transmissi...,NaN,0.954959,0.394643,NaN
3,"What advanced safety features, including Forwa...",[Forward Collision - Avoidance Assist - \nJunc...,[<1-hop>\n\nSafety Airbag Driver & passenger S...,The Hyundai models offer a range of advanced s...,The Hyundai models are equipped with advanced ...,NaN,0.937321,0.805556,NaN
4,What are the features and specifications of th...,[MT (Manual transmission) I AT (Automati...,[<1-hop>\n\nTransmission Type 6-speed manual &...,The Hyundai vehicle models equipped with a 7-s...,The Hyundai vehicle models equipped with a 7-s...,NaN,0.997428,0.958333,NaN